[tool.poetry]
name = "my-project"
version = "0.1.0"
description = "No description provided."
license = "MIT"
authors = [
    "Jane Doe <jane.doe@example.com>"
]
readme = "README.md"
repository = "https://github.com/janedoe/my-project"
keywords = ["my-project"]
packages = [
    { include = "my_project" },
]


[tool.poetry.dependencies]
python = ">=3.8,<=3.12"
click = "8.*"


[tool.poetry.group.dev.dependencies]
copier = "9.*"
pre-commit = "3.*"
ruff = "0.*"
isort = "5.*"
black = "24.*"

[tool.poetry.scripts]
my-project = 'my_project.console:run'

[tool.isort]
profile = "black"
src_paths = ["my_project", "tests"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
